import ramda from 'ramda';
export const R = ramda;
// type StringArray = string[];
// tslint:disable-next-line: no-any
export const stocklist0: { [some: string]: any[] } = {
  Symbol: [
    'Symbol',
    'Company	Earnings Call Time	EPS Estimate	Reported EPS	Surprise(%)',
  ],

  ADC: ['ADC', 'Agree Realty Corp	After Market Close	0.42	-	-'],
  AI: ['AI', 'Arlington Asset Investment Corp	Time Not Supplied	-	-	-'],
  AMTD: ['AMTD', 'TD Ameritrade Holding Corp	After Market Close	0.98	-	-'],
  ARCT: ['ARCT', 'Arcturus Therapeutics Ltd	Time Not Supplied	-	-	-'],
  AWRE: ['AWRE', 'Aware Inc	Time Not Supplied	-	-	-'],
  AIW: ['AIW', 'Arlington Asset Investment Corp	Time Not Supplied	-	-	-'],
  ACC: ['ACC', 'American Campus Communities Inc	After Market Close	-0.01	-	-'],
  KYN: [
    'KYN',
    'Kayne Anderson MLP/Midstream Investment Co	Time Not Supplied	-	-	-',
  ],
  CCBG: ['CCBG', 'Capital City Bank Group Inc	Before Market Open	0.45	-	-'],
  HOPE: ['HOPE', 'Hope Bancorp Inc	After Market Close	0.32	-	-'],
  BMRC: ['BMRC', 'Bank of Marin Bancorp	TAS	0.61	-	-'],
  WASH: ['WASH', 'Washington Trust Bancorp Inc	After Market Close	0.96	-	-'],
  BXS: ['BXS', 'Bancorpsouth Bank	After Market Close	0.61	-	-'],
  IBTX: ['IBTX', 'Independent Bank Group Inc	TAS	1.34	-	-'],
  BIOL: ['BIOL', 'BIOLASE Inc	After Market Close	-0.13	-	-'],
  ONB: ['ONB', 'Old National Bancorp	TAS	0.34	-	-'],
  CBU: ['CBU', 'Community Bank System Inc	TAS	0.81	-	-'],
  LOAN: ['LOAN', 'Manhattan Bridge Capital Inc	Before Market Open	0.11	-	-'],
  RBCAA: ['RBCAA', 'Republic Bancorp Inc	Before Market Open	0.75	0.83	+10.67'],
  FNCB: ['FNCB', 'FNCB Bancorp Inc	After Market Close	-	-	-'],
  FMAO: ['FMAO', 'Farmers & Merchants Bancorp Inc	Time Not Supplied	0.41	-	-'],
  OFG: ['OFG', 'OFG Bancorp	TAS	0.43	-	-'],
  RNDB: ['RNDB', 'Randolph Bancorp Inc	Time Not Supplied	0.26	-	-'],
  TRST: ['TRST', 'TrustCo Bank Corp N Y	After Market Close	0.15	-	-'],
  PWOD: ['PWOD', 'Penns Woods Bancorp Inc	Time Not Supplied	-	-	-'],
  FBSS: ['FBSS', 'Fauquier Bankshares Inc	Time Not Supplied	-	-	-'],
  FNLC: ['FNLC', 'First Bancorp Inc	After Market Close	-	-	-'],
  PEBK: ['PEBK', 'Peoples Bancorp of North Carolina Inc	Time Not Supplied	-	-	-'],
  ZION: ['ZION', 'Zions Bancorporation NA	After Market Close	1.09	-	-'],
  FCBC: ['FCBC', 'First Community Bankshares Inc	TAS	0.55	-	-'],
  SFBS: ['SFBS', 'ServisFirst Bancshares Inc	TAS	0.65	-	-'],
  NWBI: ['NWBI', 'Northwest Bancshares Inc	Before Market Open	0.26	-	-'],
  ZIONW: ['ZIONW', 'Zions Bancorporation NA	After Market Close	-	-	-'],
  BFIN: ['BFIN', 'BankFinancial Corp	Time Not Supplied	0.22	-	-'],
  MCBC: ['MCBC', 'Macatawa Bank Corp	Time Not Supplied	0.21	-	-'],
  SHBI: ['SHBI', 'Shore Bancshares Inc	After Market Close	0.32	-	-'],
  HXL: ['HXL', 'Hexcel Corp	After Market Close	0.88	-	-'],
  CREX: ['CREX', 'Creative Realities Inc	Time Not Supplied	-0.01	-	-'],
  FDEF: ['FDEF', 'First Defiance Financial Corp	After Market Close	0.6	-	-'],
  TCF: ['TCF', 'TCF Financial Corp	Before Market Open	0.5	-	-'],
  RNST: ['RNST', 'Renasant Corp	After Market Close	0.74	-	-'],
  CHFC: ['CHFC', 'Chemical Financial Corp	Time Not Supplied	1.01	-	-'],
  XRX: ['XRX', 'Xerox Corp	After Market Close	0.86	-	-'],
  EFSC: ['EFSC', 'Enterprise Financial Services Corp	After Market Close	1	-	-'],
  CHCO: ['CHCO', 'City Holding Co	Before Market Open	1.32	-	-'],
  NUE: ['NUE', 'Nucor Corp	TAS	0.81	-	-'],
  THFF: ['THFF', 'First Financial Corp	Time Not Supplied	0.92	-	-'],
  CE: ['CE', 'Celanese Corp	After Market Close	2.51	-	-'],
  HAL: ['HAL', 'Halliburton Co	TAS	0.34	-	-'],
  SLM: ['SLM', 'SLM Corp	Time Not Supplied	0.26	-	-'],
  DNBF: ['DNBF', 'DNB Financial Corp	Time Not Supplied	0.71	-	-'],
  FUNC: ['FUNC', 'First United Corp	Time Not Supplied	-	-	-'],
  CDNS: ['CDNS', 'Cadence Design Systems Inc	After Market Close	0.51	-	-'],
  WSFS: ['WSFS', 'WSFS Financial Corp	After Market Close	0.87	-	-'],
  TACO: ['TACO', 'Del Taco Restaurants Inc	After Market Close	0.14	-	-'],
  RUSHA: ['RUSHA', 'Rush Enterprises Inc	Time Not Supplied	1.05	-	-'],
  PETS: ['PETS', 'Petmed Express Inc	TAS	0.26	-	-'],
  SPN: ['SPN', 'Superior Energy Services Inc	Time Not Supplied	-0.2	-	-'],
  HLX: ['HLX', 'Helix Energy Solutions Group Inc	After Market Close	0.16	-	-'],
  ELS: ['ELS', 'Equity LifeStyle Properties Inc	After Market Close	0.32	-	-'],
  SPNV: ['SPNV', 'Superior Energy Services Inc	Time Not Supplied	-0.2	-	-'],
  WSBF: [
    'WSBF',
    'Waterstone Financial Inc (Wisconsin)	After Market Close	0.31	-	-',
  ],
  WBC: ['WBC', 'WABCO Holdings Inc	Before Market Open	1.66	-	-'],
  CKH: ['CKH', 'SEACOR Holdings Inc	Time Not Supplied	0.49	-	-'],
  HMST: ['HMST', 'HomeStreet Inc	After Market Close	0.33	-	-'],
  HSTM: ['HSTM', 'HealthStream Inc	After Market Close	0.06	-	-'],
  TSS: ['TSS', 'Total System Services Inc	Time Not Supplied	1.22	-	-'],
  REPR: ['REPR', 'Repro Med Systems Inc	After Market Close	-	-	-'],
  UTMD: ['UTMD', 'Utah Medical Products Inc	Before Market Open	-	-	-'],
  UTI: ['UTI', 'Universal Technical Institute Inc	After Market Close	-	-	-'],
  LLL: ['LLL', 'L3 Technologies Inc	Before Market Open	-	-	-'],
  TR: ['TR', 'Tootsie Roll Industries Inc	After Market Close	-	-	-'],
  RWWI: ['RWWI', 'Rand Worldwide Inc	Time Not Supplied	-	-	-'],
  MDSO: ['MDSO', 'Medidata Solutions Inc	Before Market Open	0.47	-	-'],
  NPK: ['NPK', 'National Presto Industries Inc	After Market Close	-	-	-'],
  LII: ['LII', 'Lennox International Inc	TAS	3.41	-	-'],
  VYEY: ['VYEY', 'Victory Oilfield Tech Inc	After Market Close	-	-	-'],
  MRTN: ['MRTN', 'Marten Transport Ltd	After Market Close	0.28	'],
};

export const stocklist2 = Object.values(stocklist0);
export const splitValues = stocklist2.forEach(item => {
  item[1] = item[1].split('\t');
});
// export const before = stocklist2.filter(
//   item => item[1].indexOf('Before Market Open') !== -1
// );
// export const after = stocklist2.filter(
//   item => item[1].indexOf('After Market Close') !== -1
// );
console.log(stocklist2);
export const stocklist1 = [
  'ADC',
  'AI',
  'AMTD',
  'ARCT',
  'AWRE',
  'AIW',
  'ACC',
  'KYN',
  'CCBG',
  'HOPE',
  'BMRC',
  'WASH',
  'BXS',
  'IBTX',
  'BIOL',
  'ONB',
  'CBU',
  'LOAN',
  'RBCAA',
  'FNCB',
  'FMAO',
  'OFG',
  'RNDB',
  'TRST',
  'PWOD',
  'FBSS',
  'FNLC',
  'PEBK',
  'ZION',
  'FCBC',
  'SFBS',
  'NWBI',
  'ZIONW',
  'BFIN',
  'MCBC',
  'SHBI',
  'HXL',
  'CREX',
  'FDEF',
  'TCF',
  'RNST',
  'CHFC',
  'XRX',
  'EFSC',
  'CHCO',
  'NUE',
  'THFF',
  'CE',
  'HAL',
  'SLM',
  'DNBF',
  'FUNC',
  'CDNS',
  'WSFS',
  'TACO',
  'RUSHA',
  'PETS',
  'SPN',
  'HLX',
  'ELS',
  'SPNV',
  'WSBF',
  'WBC',
  'CKH',
  'HMST',
  'HSTM',
  'TSS',
  'REPR',
  'UTMD',
  'UTI',
  'LLL',
  'TR',
  'RWWI',
  'MDSO',
  'NPK',
  'LII',
  'VYEY',
  'MRTN',
];
