version: "3.8"

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6480:6379
    networks:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:

volumes:
  db-data:
