// /* eslint-disable import/no-unassigned-import */
// import { main } from './redis-modeling';

import NULL from '../../resources/side-effects/proxies/client';
import { main } from './redis-modeling';

main();
// //.catch(error => errorlog('in main from redis-modeling', error.message));
NULL;

// console.log('hello today')
/*
import '../../circular';
import '../../private/api/AccountsCalls/_getAccounts/_getAccounts';
import '../../private/api/AccountsCalls/_getActivities/_getActivities';
import '../../private/api/AccountsCalls/_getBalances/_getBalances';
import '../../private/api/AccountsCalls/_getBalances/_myBalances';
import '../../private/api/AccountsCalls/_getExecutions/_getExecutions';
import '../../private/api/AccountsCalls/_getOrders/_getOrders';
import '../../private/api/AccountsCalls/_getOrders/_getOrdersByIds';
import '../../private/api/AccountsCalls/_getPositions/_getPositions';
import '../../private/api/AccountsCalls/_getServerTime/_getServerTime';
import '../../private/api/MarketsCalls/_getCandles/_getCandles';
import '../../private/api/MarketsCalls/_getMarkets/_getMarkets';
import '../../private/api/MarketsCalls/_getMarketsQuotesOptions';
import '../../private/api/MarketsCalls/_getMarketsQuotesOptions/_getMarketsQuotesOptions';
import '../../private/api/MarketsCalls/_getMarketsQuotesOptions/_getQuotesOptionsByIds';
import '../../private/api/MarketsCalls/_getMarketsQuotesOptions/_getQuotesOptionsFilter';
import '../../private/api/MarketsCalls/_getMarketsQuotesStrategies';
import '../../private/api/MarketsCalls/_getMarketsQuotesStrategies/_getMarketsQuotesStrategies';
import '../../private/api/MarketsCalls/_getOptionsById/_getOptionsById';
import '../../private/api/MarketsCalls/_getQuotesByIds/_getQuotesByIds';
import '../../private/api/MarketsCalls/_getSymbolsByIds/_getSymbolsByIds';
import '../../private/api/MarketsCalls/_getSymbolSearch';
import '../../private/api/MarketsCalls/_getSymbolSearch/_getSymbolSearch';
import '../../private/api/MarketsCalls/_getSymbolSearch/_getSymbolSearchAll';
import '../../private/api/MarketsCalls/_getSymbolSearch/_getSymbolSearchCount';
import '../../private/api/_getQuestradeApi';
import '../../private/auth/credentialsFactory';
import '../../private/auth/credentialsFactory/_buildCredentialsFromToken';
import '../../private/auth/credentialsFactory/_credentialsFactory';
import '../../private/auth/credentialsFactory/_defaultCredentials';
import '../../private/auth/credentialsFactory/_emptyCredentials';
import '../../private/auth/credentialsFactory/_getPrimaryAccountNumber';
import '../../private/auth/xx-http-auth-xx';
import '../../private/core/end-point-connector';
import '../../private/core/end-point-connector/_coreApiConfig';
import '../../private/core/end-point-connector/_coreApiFunction';
import '../../private/core/end-point-connector/_echoStatus';
import '../../private/core/end-point-connector/_logErrors';
import '../../private/core/end-point-connector/_rateLimiter';
import '../../private/core/end-point-connector/_updateCredentials';
import '../../private/core/requestPerSecondLimit';
import '../../private/core/requestPerSecondLimit/callToPop';
import '../../private/core/requestPerSecondLimit/CORE_PerSecond_Limiter';
import '../../private/core/requestPerSecondLimit/logData';
import '../../private/core/requestPerSecondLimit/logRemanings';
import '../../private/core/requestPerSecondLimit/remainingRequests';
import '../../private/core/requestPerSecondLimit/remaningTimeString';
import '../../private/core/XX-http-data-end-point-connector-XX';
import '../../private/routes';
import '../../private/routes/clientAccountGetApi/endpointFormatAccount/_endpointFormatAccount';
import '../../private/routes/clientAccountGetApi/_clientAccountGetApi';
import '../../private/routes/clientGetApi/_clientGetApi';
import '../../private/routes/clientPostApi/_clientPostApi';
import '../../public';
import '../../public/questradeAPI';
import '../../public/questradeChainAPI';
import '../../public/redeemToken';
import '../../resources/side-effects';
import '../../resources/side-effects/auth/validateToken';
import '../../resources/side-effects/auth/writeToken';
import '../../resources/side-effects/default-behaviour';
import '../../resources/side-effects/default-behaviour/client';
import '../../resources/side-effects/default-behaviour/ech0';
import '../../resources/side-effects/default-behaviour/echo';
import '../../resources/side-effects/default-behaviour/errorlog';
import '../../resources/side-effects/default-behaviour/getHash';
import '../../resources/side-effects/default-behaviour/getHttpClient';
import '../../resources/side-effects/default-behaviour/getMyToken';
import '../../resources/side-effects/default-behaviour/infolog';
import '../../resources/side-effects/default-behaviour/makeTedis';
import '../../resources/side-effects/default-behaviour/setMyToken';
import '../../resources/side-effects/default-behaviour/tablelog';
import '../../resources/side-effects/default-behaviour/warnlog';
import '../../resources/side-effects/proxies';
import '../../resources/side-effects/proxies/client/http-client-console-log-hashes-handler-class';
import '../../resources/side-effects/proxies/client/redis-client-proxy-handler-class';
import '../../resources/side-effects/proxies/core/client-proxy-handler-factory-function';
import '../../resources/side-effects/proxies/core/reflexion-logger-proxy-handler-abstarct-class';
import '../../resources/side-effects/types';
import '../../resources/side-effects/typescript';
import '../../resources/side-effects/typescript/client';
import '../../resources/side-effects/typescript/client/Cancel';
import '../../resources/side-effects/typescript/client/Canceler';
import '../../resources/side-effects/typescript/client/CancelStatic';
import '../../resources/side-effects/typescript/client/CancelToken';
import '../../resources/side-effects/typescript/client/CancelTokenSource';
import '../../resources/side-effects/typescript/client/CancelTokenStatic';
import '../../resources/side-effects/typescript/client/ClientError';
import '../../resources/side-effects/typescript/client/ClientInstance';
import '../../resources/side-effects/typescript/client/ClientInterceptorManager';
import '../../resources/side-effects/typescript/client/ClientPromise';
import '../../resources/side-effects/typescript/client/ClientRequestConfig';
import '../../resources/side-effects/typescript/client/ClientResponse';
import '../../resources/side-effects/typescript/client/ClientStatic';
import '../../resources/side-effects/typescript/client/ClientTransformer';
import '../../resources/side-effects/typescript/proxy/proxy-handler-options';
import '../../types-api';
import '../../utils';
import '../../utils/create-url-and-data-hashes';
import '../../utils/curry';
import '../../utils/dates';
import '../../utils/fantasy-birds/curry';
import '../../utils/get-qt-url-path-from-args';
import '../../utils/getHash';
import '../../utils/helpers/get-symbol-id-by-stock-symbol';
import '../../utils/mkdirp';
import '../../utils/perSeconds';
import '../../utils/timeutil';
import '../../utils/types';
import '../../utils/void0';
 */
