export type {
  CachedApiResponse,
  Cancel,
  Canceler,
  CancelStatic,
  CancelToken,
  CancelTokenSource,
  CancelTokenStatic,
  ClientError,
  ClientInstance,
  ClientInterceptorManager,
  ClientPromise,
  ClientRequestConfig,
  ClientResponse,
  ClientStatic,
  ClientTransformer,
  IoRedis,
  ProxyHandlerOptions,
  StaticJSONCache,
} from './typescript';
export type { Tedis } from 'tedis';
