[
  [
    "src/private/api/AccountsCalls/_getAccounts/_getAccounts.js",
    "src/private/routes/index.js",
    "src/private/routes/clientGetApi/_clientGetApi.js",
    "src/private/core/_coreApiFunction.js",
    "src/private/core/XX-try-to-get-data-from-http-client-XX.js",
    "src/private/core/requestPerSecondLimit/index.js",
    "src/private/core/requestPerSecondLimit/CORE_PerSecond_Limiter.js",
    "src/resources/side-effects/index.js",
    "src/resources/side-effects/default-behaviour/index.js",
    "src/resources/side-effects/default-behaviour/validateToken.js",
    "src/resources/side-effects/auth/_validateToken.js",
    "src/private/auth/credentialsFactory/index.js",
    "src/private/auth/credentialsFactory/_credentialsFactory.js"
  ],
  [
    "src/private/routes/index.js",
    "src/private/routes/clientGetApi/_clientGetApi.js",
    "src/private/core/_coreApiFunction.js",
    "src/private/core/XX-try-to-get-data-from-http-client-XX.js",
    "src/private/core/requestPerSecondLimit/index.js",
    "src/private/core/requestPerSecondLimit/CORE_PerSecond_Limiter.js",
    "src/resources/side-effects/index.js",
    "src/resources/side-effects/default-behaviour/index.js",
    "src/resources/side-effects/default-behaviour/validateToken.js",
    "src/resources/side-effects/auth/_validateToken.js",
    "src/private/auth/credentialsFactory/index.js",
    "src/private/auth/credentialsFactory/_credentialsFactory.js",
    "src/private/api/AccountsCalls/_getServerTime/_getServerTime.js"
  ],
  [
    "src/resources/side-effects/index.js",
    "src/resources/side-effects/default-behaviour/index.js",
    "src/resources/side-effects/default-behaviour/validateToken.js",
    "src/resources/side-effects/auth/_validateToken.js",
    "src/private/auth/credentialsFactory/index.js",
    "src/private/auth/credentialsFactory/_credentialsFactory.js",
    "src/private/auth/clientCredentials_oAUTH/xx-http-auth-xx.js"
  ],
  [
    "src/resources/side-effects/index.js",
    "src/resources/side-effects/default-behaviour/index.js",
    "src/resources/side-effects/default-behaviour/validateToken.js",
    "src/resources/side-effects/auth/_validateToken.js",
    "src/private/auth/credentialsFactory/index.js",
    "src/private/auth/credentialsFactory/_credentialsFactory.js",
    "src/private/auth/credentialsFactory/_getPrimaryAccountNumber.js"
  ],
  [
    "src/resources/side-effects/index.js",
    "src/resources/side-effects/default-behaviour/index.js",
    "src/resources/side-effects/default-behaviour/validateToken.js",
    "src/resources/side-effects/auth/_validateToken.js",
    "src/private/auth/credentialsFactory/index.js",
    "src/private/auth/credentialsFactory/_credentialsFactory.js"
  ]
]
